<?php
session_start();
require_once 'includes/db.php';
if (!isset($_SESSION['user_id']) || $_SESSION['user_role'] !== 'student') { header('Location: login.php'); exit; }

$pdo = getDB();
$userId = $_SESSION['user_id'];

// Handle Payment Submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $reqId = $_POST['request_id'];
    $method = $_POST['method'];
    $trxRef = $_POST['generated_ref']; // Recieved from the hidden input
    
    try {
        $pdo->beginTransaction();

        // 1. Insert into payments table using the reference generated by the student's browser
        $stmt = $pdo->prepare("INSERT INTO payments (request_id, amount, payment_method, transaction_reference, status) 
                               SELECT id, total_amount, ?, ?, 'pending' FROM requests WHERE id = ?");
        $stmt->execute([$method, $trxRef, $reqId]);

        // 2. Mark request as 'paid' status and notify admin
        $pdo->prepare("UPDATE requests SET status = 'paid', is_viewed = FALSE WHERE id = ?")->execute([$reqId]);

        $pdo->commit();
        $success = "Payment details submitted! Transaction Ref: <strong>$trxRef</strong>";
    } catch (Exception $e) {
        $pdo->rollBack();
        $error = "Payment failed: " . $e->getMessage();
    }
}

// Fetch requests that are NOT yet released
$requests = $pdo->prepare("SELECT r.*, dt.name as document_name FROM requests r 
                           JOIN document_types dt ON r.document_type_id = dt.id 
                           WHERE r.user_id = ? AND r.status IN ('pending', 'paid', 'approved') 
                           ORDER BY r.created_at DESC");
$requests->execute([$userId]);
$rows = $requests->fetchAll();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Payments — WildDocuments</title>
    <link rel="stylesheet" href="css/styles.css">
    <style>
        .badge-paid { background:#EFF6FF; color:#1D4ED8; }
        .payment-summary {
            background: var(--off-white);
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
            border: 1px dashed var(--border);
        }
        .summary-item { display: flex; justify-content: space-between; margin-bottom: 8px; font-size: 0.9rem; }
        .summary-item span:first-child { color: var(--text-muted); }
        .summary-item span:last-child { font-weight: 600; color: var(--text-dark); }
        #display_trx { font-family: monospace; color: var(--crimson); letter-spacing: 0.5px; }
    </style>
</head>
<body>
<?php include 'includes/student_navbar.php'; ?>
<div class="app-layout">
    <?php include 'includes/student_sidebar.php'; ?>
    <main class="main-content" style="background: var(--bg-light); min-height: 100vh; padding-bottom: 50px;">
        <div class="dashboard-page">
            <div class="page-title-row">
                <div>
                    <h2>My Payments</h2>
                    <p>Settle your fees to begin document processing.</p>
                </div>
            </div>
            
            <?php if(isset($success)) echo "<div class='alert alert-success'>$success</div>"; ?>
            <?php if(isset($error)) echo "<div class='alert alert-error'>$error</div>"; ?>

            <div class="card">
                <div class="card__header"><h3>Payable Documents</h3></div>
                <div class="card__body" style="padding:0">
                    <table class="data-table">
                        <thead>
                            <tr>
                                <th>Ref #</th>
                                <th>Document</th>
                                <th>Amount</th>
                                <th>Status</th>
                                <th style="text-align:center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (empty($rows)): ?>
                                <tr><td colspan="5" style="text-align:center; padding:30px; color:var(--text-muted)">No pending payments.</td></tr>
                            <?php endif; ?>
                            <?php foreach($rows as $r): ?>
                            <tr>
                                <td style="font-weight:700; color:var(--crimson)"><?= $r['reference_number'] ?></td>
                                <td><?= $r['document_name'] ?></td>
                                <td style="font-weight:600">₱<?= number_format($r['total_amount'], 2) ?></td>
                                <td><span class="badge badge-<?= $r['status'] ?>"><?= ucfirst($r['status']) ?></span></td>
                                <td style="text-align:center">
                                    <?php if($r['status'] === 'pending'): ?>
                                        <button class="btn btn-primary btn-sm" onclick="openPay('<?= $r['id'] ?>', '<?= $r['document_name'] ?>', '<?= $r['total_amount'] ?>')">Pay Now</button>
                                    <?php else: ?>
                                        <div style="display:flex; flex-direction:column; align-items:center">
                                            <span style="color:#16a34a; font-size:0.75rem; font-weight:700">✓ Details Submitted</span>
                                        </div>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </main>
</div>

<!-- Payment Modal -->
<div class="modal-overlay" id="payModal">
    <div class="modal" style="max-width: 400px; text-align: left;">
        <h3 style="margin-bottom: 5px;">Confirm Payment</h3>
        <p style="font-size: 0.85rem; color: var(--text-muted); margin-bottom: 20px;">Please review the auto-generated receipt info.</p>
        
        <div class="payment-summary">
            <div class="summary-item">
                <span>Document:</span>
                <span id="display_doc">-</span>
            </div>
            <div class="summary-item">
                <span>Amount:</span>
                <span id="display_amt">₱0.00</span>
            </div>
            <div class="summary-item">
                <span>TRX Reference:</span>
                <span id="display_trx">TRX-00000000-0000</span> <!-- DISPLAYED HERE BEFORE CONFIRM -->
            </div>
        </div>

        <form method="POST">
            <input type="hidden" name="request_id" id="pay_req_id">
            <!-- HIDDEN INPUT TO SEND THE GENERATED ID TO PHP -->
            <input type="hidden" name="generated_ref" id="hidden_trx_ref">
            
            <div class="form-group">
                <label class="form-label">Select Payment Method</label>
                <select name="method" class="form-control" required>
                    <option value="GCash">GCash</option>
                    <option value="Maya">Maya</option>
                    <option value="Bank Transfer">Bank Transfer</option>
                </select>
            </div>

            <div style="display: flex; gap: 10px; margin-top: 25px;">
                <button type="button" class="btn btn-ghost btn-block" onclick="closePay()">Cancel</button>
                <button type="submit" class="btn btn-primary btn-block">Confirm & Pay</button>
            </div>
        </form>
    </div>
</div>

<script>
// Logic to generate TRX ID instantly
function generateTransactionID() {
    const now = new Date();
    const datePart = now.getFullYear() + 
                     String(now.getMonth() + 1).padStart(2, '0') + 
                     String(now.getDate()).padStart(2, '0');
    
    // Generate 8 random uppercase characters/numbers
    const randomPart = Math.random().toString(36).substring(2, 10).toUpperCase();
    
    return `TRX-${datePart}-${randomPart}`;
}

function openPay(id, doc, amt) {
    // 1. Set basic details
    document.getElementById('pay_req_id').value = id;
    document.getElementById('display_doc').innerText = doc;
    document.getElementById('display_amt').innerText = '₱' + parseFloat(amt).toFixed(2);
    
    // 2. GENERATE ID IMMEDIATELY
    const newTrxID = generateTransactionID();
    
    // 3. SHOW ID IN UI AND SET IN HIDDEN FIELD
    document.getElementById('display_trx').innerText = newTrxID;
    document.getElementById('hidden_trx_ref').value = newTrxID;
    
    // 4. Open Modal
    document.getElementById('payModal').classList.add('open');
}

function closePay() { document.getElementById('payModal').classList.remove('open'); }

window.onclick = function(event) {
    if (event.target == document.getElementById('payModal')) closePay();
}
</script>

<?php include 'includes/footer.php'; ?>
</body>
</html>